-- Drop the restrictive check constraint on 'type' column (likely auto-generated by Hibernate)
ALTER TABLE assignments DROP CONSTRAINT IF EXISTS assignments_type_check;

-- Make 'type' nullable so we can ignore it and use 'assignment_type' instead
ALTER TABLE assignments ALTER COLUMN type DROP NOT NULL;

-- Ensure assignment_type has a default if not already
-- ALTER TABLE assignments ALTER COLUMN assignment_type SET DEFAULT 'FILE_SUBMISSION';
