/**
 * Maritime Standards Keyword Catalog
 * Source: maritime-standards-keywords.json (STCW Manila 2010, SOLAS, MARPOL, COLREGS)
 * 50 standards across 5 standard types, bilingual (Vietnamese + English)
 *
 * Scoring algorithm (per JSON usageInstructions):
 *   >= 3 keyword hits → strong suggestion (show + auto-highlight)
 *   1–2 keyword hits  → possible suggestion (show, lower priority)
 */

export interface StdKwEntry {
  code: string;
  standardType: 'STCW' | 'SOLAS' | 'MARPOL' | 'COLREGs' | 'IMO Codes';
  category: string;
  title: string;
  titleEn: string;
  keywords: string[];
}

export interface KwMatch {
  code: string;
  standardType: string;
  category: string;
  title: string;
  titleEn: string;
  score: number;
  matchedKeywords: string[];
  /** strong = score >= 3, possible = score 1-2 */
  confidence: 'strong' | 'possible';
}

export function matchStandards(text: string, limit = 8): KwMatch[] {
  if (!text || text.trim().length < 2) return [];
  const lower = text.toLowerCase();
  const results: KwMatch[] = [];

  for (const entry of KW_DB) {
    const matched: string[] = [];
    for (const kw of entry.keywords) {
      if (lower.includes(kw.toLowerCase())) {
        matched.push(kw);
      }
    }
    if (matched.length >= 1) {
      results.push({
        code: entry.code,
        standardType: entry.standardType,
        category: entry.category,
        title: entry.title,
        titleEn: entry.titleEn,
        score: matched.length,
        matchedKeywords: matched.slice(0, 5),
        confidence: matched.length >= 3 ? 'strong' : 'possible',
      });
    }
  }

  return results.sort((a, b) => b.score - a.score).slice(0, limit);
}

export const KW_DB: StdKwEntry[] = [
  // ── STCW ──────────────────────────────────────────────────────────────────
  { code: 'A-II/1', standardType: 'STCW', category: 'Deck', title: 'Sĩ quan trực ca boong - Cấp vận hành', titleEn: 'Navigational watch at operational level', keywords: ['hải đồ', 'định hướng', 'celestial', 'navigation', 'radar', 'ARPA', 'ECDIS', 'vị trí tàu', 'lượng âm', 'tides', 'currents', 'bridge teamwork', 'hải văn', 'thiên văn', 'sextant', 'máy định vị', 'chart', 'plotting', 'course', 'speed', 'gyro compass', 'magnetic compass', 'autopilot', 'lookout', 'watch keeping', 'trực ca', 'quan sát', 'VHF', 'communication'] },
  { code: 'A-II/2', standardType: 'STCW', category: 'Deck', title: 'Sĩ quan trực ca boong - Cấp quản lý', titleEn: 'Navigational watch at management level', keywords: ['voyage planning', 'kế hoạch hành trình', 'weather routing', 'ETA', 'passage plan', 'appraisal', 'execution', 'monitoring', 'ECDIS', 'radar', 'ARPA', 'GPS', 'celestial navigation', 'astronomical', 'sight reduction', 'meridian passage', 'ex-meridian', 'great circle', 'rhumb line', 'composite sailing', 'current sailing', 'tidal stream'] },
  { code: 'A-II/3', standardType: 'STCW', category: 'Deck', title: 'Sĩ quan trực ca tàu < 500 GT', titleEn: 'Officer in charge of navigational watch on vessels less than 500 GT', keywords: ['coastal navigation', 'pilotage', 'small vessel', 'inshore', 'fishing vessel', 'chart work', 'position fixing', 'compass', 'GPS', 'radar', 'VHF', 'basic seamanship', 'mooring', 'anchoring'] },
  { code: 'A-II/4', standardType: 'STCW', category: 'Deck', title: 'Thủy thủ trực ca boong', titleEn: 'Rating forming part of navigational watch', keywords: ['helm', 'bánh lái', 'lookout', 'quan sát', 'rope work', 'dây thừng', 'knots', 'nút thừng', 'splicing', 'mooring operations', 'neo đậu', 'anchor watch', 'cleaning', 'maintenance', 'bảo dưỡng', 'painting', 'sơn', 'chipping'] },
  { code: 'A-II/5', standardType: 'STCW', category: 'Deck', title: 'Thủy thủ giỏi boong', titleEn: 'Rating as able seafarer deck', keywords: ['able seaman', 'AB', 'advanced seamanship', 'rigging', 'cargo handling', 'xếp dỡ hàng', 'hatch cover', 'derrick', 'crane', 'winch', 'windlass', 'capstan', 'mooring equipment', 'wire rope', 'dây cáp', 'maintenance', 'inspection'] },
  { code: 'A-III/1', standardType: 'STCW', category: 'Engine', title: 'Sĩ quan Ca máy - Cấp vận hành', titleEn: 'Engineering watch at operational level', keywords: ['máy chính', 'động cơ', 'machinery', 'diesel engine', 'main engine', 'auxiliary engine', 'boiler', 'nồi hơi', 'generator', 'máy phát điện', 'pumping', 'bơm', 'bôi trơn', 'cooling', 'làm mát', 'fuel', 'nhiên liệu', 'lubrication', 'engine room', 'buồng máy', 'watch keeping', 'trực ca', 'operation', 'vận hành', 'monitoring', 'giám sát', 'alarm', 'báo động'] },
  { code: 'A-III/2', standardType: 'STCW', category: 'Engine', title: 'Sĩ quan Ca máy - Cấp quản lý', titleEn: 'Engineering watch at management level', keywords: ['engine management', 'quản lý máy', 'maintenance planning', 'kế hoạch bảo dưỡng', 'PMS', 'planned maintenance', 'overhaul', 'đại tu', 'troubleshooting', 'fault finding', 'repair', 'sửa chữa', 'diesel theory', 'thermodynamics', 'nhiệt động học', 'combustion', 'cháy', 'turbocharger', 'scavenging', 'fuel injection', 'phun nhiên liệu'] },
  { code: 'A-III/3', standardType: 'STCW', category: 'Engine', title: 'Sĩ quan điện - Cấp vận hành', titleEn: 'Electro-technical officer', keywords: ['electrical', 'điện', 'electronics', 'điện tử', 'automation', 'tự động hóa', 'control systems', 'hệ thống điều khiển', 'switchboard', 'tủ điện', 'generator', 'motor', 'động cơ điện', 'transformer', 'biến áp', 'circuit breaker', 'wiring', 'dây điện', 'insulation', 'cách điện'] },
  { code: 'A-III/4', standardType: 'STCW', category: 'Engine', title: 'Thủy thủ trực ca máy', titleEn: 'Rating forming part of engine-room watch', keywords: ['oiler', 'wiper', 'engine room', 'buồng máy', 'watch keeping', 'trực ca', 'oil sampling', 'lấy mẫu dầu', 'sounding', 'đo mức', 'cleaning', 'vệ sinh', 'bilge', 'nước đáy tàu', 'greasing', 'bôi mỡ', 'tool handling', 'dụng cụ'] },
  { code: 'A-III/5', standardType: 'STCW', category: 'Engine', title: 'Thủy thủ giỏi máy', titleEn: 'Rating as able seafarer engine', keywords: ['able engine', 'skilled rating', 'maintenance', 'bảo dưỡng', 'repair', 'sửa chữa', 'workshop', 'xưởng', 'lathe', 'máy tiện', 'welding', 'hàn', 'fitting', 'lắp ráp', 'machining', 'gia công'] },
  { code: 'A-IV/2', standardType: 'STCW', category: 'Radio', title: 'Sĩ quan vô tuyến điện GMDSS', titleEn: 'GMDSS radio operator', keywords: ['GMDSS', 'radio', 'vô tuyến', 'VHF', 'MF', 'HF', 'INMARSAT', 'EPIRB', 'SART', 'DSC', 'distress', 'khẩn cấp', 'SAR', 'search and rescue', 'tìm kiếm cứu nạn', 'communication', 'liên lạc', 'maritime safety information', 'MSI', 'NAVTEX'] },
  { code: 'A-V/1-1', standardType: 'STCW', category: 'Tanker', title: 'Huấn luyện cơ bản tàu chở dầu', titleEn: 'Basic training for oil tanker', keywords: ['oil tanker', 'tàu chở dầu', 'crude oil', 'dầu thô', 'petroleum', 'cargo operations', 'loading', 'xếp hàng', 'discharging', 'dỡ hàng', 'tank cleaning', 'rửa két', 'inert gas', 'khí trơ', 'COW', 'crude oil washing', 'cargo pump', 'bơm hàng', 'pipeline', 'đường ống', 'manifold'] },
  { code: 'A-V/1-2', standardType: 'STCW', category: 'Tanker', title: 'Huấn luyện cơ bản tàu chở hóa chất', titleEn: 'Basic training for chemical tanker', keywords: ['chemical tanker', 'tàu chở hóa chất', 'chemicals', 'hóa chất', 'hazardous cargo', 'hàng nguy hiểm', 'compatibility', 'tương thích', 'segregation', 'phân tách', 'IBC Code', 'MSDS', 'safety data sheet', 'protective equipment', 'PPE', 'cargo handling', 'tank coating', 'lớp phủ két'] },
  { code: 'A-V/1-3', standardType: 'STCW', category: 'Tanker', title: 'Huấn luyện cơ bản tàu chở khí hóa lỏng', titleEn: 'Basic training for liquefied gas tanker', keywords: ['LNG', 'LPG', 'gas tanker', 'tàu chở khí', 'liquefied gas', 'khí hóa lỏng', 'cryogenic', 'nhiệt độ cực thấp', 'refrigeration', 'làm lạnh', 'insulation', 'cách nhiệt', 'IGC Code', 'cargo containment', 'boil-off', 'reliquefaction', 'hóa lỏng lại'] },
  { code: 'A-VI/1-1', standardType: 'STCW', category: 'Safety', title: 'Kỹ thuật sống sót cá nhân (PST)', titleEn: 'Personal survival techniques', keywords: ['sống sót', 'survival', 'lifeboat', 'bè cứu sinh', 'liferaft', 'phao cứu sinh', 'lifejacket', 'rời tàu', 'abandon ship', 'hạ xuống', 'immersion suit', 'thermal protective aid', 'TPA', 'distress signals', 'tín hiệu khẩn cấp', 'EPIRB', 'SART', 'flare', 'pháo hiệu', 'hypothermia', 'hạ thân nhiệt'] },
  { code: 'A-VI/1-2', standardType: 'STCW', category: 'Safety', title: 'Phòng cháy & Chữa cháy cơ bản', titleEn: 'Fire prevention and fire fighting', keywords: ['hỏa hoạn', 'cháy', 'fire', 'bình chữa cháy', 'extinguisher', 'vòi rồng', 'hydrant', 'tam giác cháy', 'thoát hiểm', 'cứu hỏa', 'foam', 'bọt', 'CO2', 'dry powder', 'bột khô', 'water mist', 'sprinkler', 'fire main', 'fire pump', 'bơm cứu hỏa', 'fire drill', 'diễn tập', 'breathing apparatus', 'SCBA', 'EEBD'] },
  { code: 'A-VI/1-3', standardType: 'STCW', category: 'Safety', title: 'Sơ cứu y tế cơ bản', titleEn: 'Elementary first aid', keywords: ['sơ cứu', 'first aid', 'CPR', 'cấp cứu', 'băng bó', 'hồi sức', 'gãy xương', 'vết thương', 'cầm máu', 'sốc', 'ép tim', 'thổi ngạt', 'bandage', 'dressing', 'splint', 'nẹp', 'burns', 'bỏng', 'shock', 'fracture', 'bleeding', 'wound', 'resuscitation', 'AED', 'choking', 'hóc nghẹn'] },
  { code: 'A-VI/1-4', standardType: 'STCW', category: 'Safety', title: 'An toàn cá nhân & Trách nhiệm xã hội', titleEn: 'Personal safety and social responsibilities', keywords: ['an toàn', 'safety', 'kỷ luật', 'môi trường', 'ô nhiễm', 'quan hệ lao động', 'sức khỏe', 'ma túy', 'rượu bia', 'ứng phó khẩn cấp', 'làm việc nhóm', 'nội quy', 'PPE', 'personal protective equipment', 'helmet', 'mũ bảo hộ', 'safety shoes', 'giày bảo hộ', 'gloves', 'găng tay', 'safety harness', 'dây an toàn', 'permit to work', 'giấy phép làm việc', 'risk assessment', 'đánh giá rủi ro'] },
  { code: 'A-VI/2-1', standardType: 'STCW', category: 'Safety', title: 'Xưởng & Bè cứu sinh', titleEn: 'Survival craft and rescue boats', keywords: ['lifeboat', 'xưởng cứu sinh', 'liferaft', 'bè cứu sinh', 'rescue boat', 'xuồng cứu nạn', 'davit', 'cần trục', 'launching', 'hạ xuống', 'embarkation', 'recovery', 'thu hồi', 'sea anchor', 'neo biển', 'survival equipment', 'trang bị sinh tồn', 'pyrotechnics', 'pháo hiệu', 'emergency rations', 'khẩu phần khẩn cấp'] },
  { code: 'A-VI/2-2', standardType: 'STCW', category: 'Safety', title: 'Xuồng cứu nạn nhanh', titleEn: 'Fast rescue boats', keywords: ['fast rescue boat', 'FRB', 'xuồng cứu nạn nhanh', 'high speed', 'tốc độ cao', 'rescue operations', 'cứu nạn', 'man overboard', 'người rơi xuống nước', 'recovery', 'thu hồi', 'launching', 'hạ xuống', 'davit operation', 'engine operation', 'vận hành động cơ'] },
  { code: 'A-VI/3', standardType: 'STCW', category: 'Safety', title: 'Chữa cháy nâng cao', titleEn: 'Advanced fire fighting', keywords: ['advanced fire fighting', 'chữa cháy nâng cao', 'fire strategy', 'chiến thuật chữa cháy', 'fire control', 'kiểm soát hỏa hoạn', 'fire inspection', 'kiểm tra phòng cháy', 'fixed system', 'hệ thống cố định', 'CO2 system', 'foam system', 'water mist', 'sprinkler system', 'fire detection', 'phát hiện cháy', 'smoke detector', 'heat detector', 'fire drill organization', 'tổ chức diễn tập', 'breathing apparatus', 'SCBA', 'fire team', 'đội chữa cháy'] },
  { code: 'A-VI/4-1', standardType: 'STCW', category: 'Safety', title: 'Y tế nâng cao', titleEn: 'Medical first aid', keywords: ['medical first aid', 'y tế nâng cao', 'medical care', 'chăm sóc y tế', 'diagnosis', 'chẩn đoán', 'treatment', 'điều trị', 'pharmacy', 'dược phẩm', 'injection', 'tiêm', 'suture', 'khâu', 'radio medical advice', 'tư vấn y tế qua radio', 'medical guide', 'hướng dẫn y tế', 'emergency medical procedures', 'thủ thuật y tế khẩn cấp'] },
  { code: 'A-VI/4-2', standardType: 'STCW', category: 'Safety', title: 'Y tế chăm sóc', titleEn: 'Medical care', keywords: ['medical care', 'y tế chăm sóc', 'ship\'s doctor', 'bác sĩ tàu', 'medical equipment', 'thiết bị y tế', 'pharmacy management', 'quản lý dược', 'telemedicine', 'y tế từ xa', 'medical examination', 'khám bệnh', 'medical records', 'hồ sơ y tế', 'dental care', 'chăm sóc răng'] },
  { code: 'A-VI/6-1', standardType: 'STCW', category: 'Security', title: 'An ninh cơ bản', titleEn: 'Security awareness', keywords: ['security', 'an ninh', 'ISPS Code', 'piracy', 'cướp biển', 'terrorism', 'khủng bố', 'security threats', 'mối đe dọa', 'security measures', 'biện pháp an ninh', 'security levels', 'cấp độ an ninh', 'restricted areas', 'khu vực hạn chế', 'access control', 'kiểm soát ra vào', 'ID check', 'kiểm tra căn cước'] },
  { code: 'A-VI/6-2', standardType: 'STCW', category: 'Security', title: 'Sĩ quan an ninh tàu (SSO)', titleEn: 'Ship security officer', keywords: ['SSO', 'ship security officer', 'sĩ quan an ninh tàu', 'security plan', 'kế hoạch an ninh', 'SSP', 'ship security plan', 'security assessment', 'đánh giá an ninh', 'security drills', 'diễn tập an ninh', 'security equipment', 'thiết bị an ninh', 'CCTV', 'security patrol', 'tuần tra', 'security reporting', 'báo cáo an ninh'] },

  // ── SOLAS ─────────────────────────────────────────────────────────────────
  { code: 'SOLAS II-2', standardType: 'SOLAS', category: 'Fire Safety', title: 'Phòng cháy, phát hiện và dập tắt hỏa hoạn', titleEn: 'Fire protection, detection and extinction', keywords: ['fire protection', 'phòng cháy', 'fire detection', 'phát hiện cháy', 'fire extinction', 'dập cháy', 'fire divisions', 'phân khu chống cháy', 'fire integrity', 'A-class division', 'B-class division', 'fire doors', 'cửa chống cháy', 'fire dampers', 'van chống cháy', 'fire main', 'fire pumps', 'bơm cứu hỏa', 'fixed fire-fighting systems', 'hệ thống chữa cháy cố định', 'smoke detectors', 'máy báo khói', 'heat detectors', 'máy báo nhiệt', 'fire alarms', 'chuông báo cháy', 'fire control plan', 'sơ đồ kiểm soát cháy'] },
  { code: 'SOLAS III', standardType: 'SOLAS', category: 'Life-Saving', title: 'Thiết bị cứu sinh (LSA)', titleEn: 'Life-saving appliances', keywords: ['thiết bị cứu sinh', 'phao', 'pyrotechnics', 'immersion suit', 'davit', 'lifeboat', 'xưởng cứu sinh', 'liferaft', 'bè cứu sinh', 'lifejacket', 'áo phao', 'lifebuoy', 'phao tròn', 'rescue boat', 'xuồng cứu nạn', 'launching appliances', 'thiết bị hạ xuống', 'embarkation ladder', 'survival craft', 'phương tiện sinh tồn', 'distress signals', 'tín hiệu khẩn cấp', 'line-throwing apparatus', 'EPIRB', 'SART'] },
  { code: 'SOLAS IV', standardType: 'SOLAS', category: 'Radio', title: 'Vô tuyến điện', titleEn: 'Radiocommunications', keywords: ['GMDSS', 'radio', 'vô tuyến', 'VHF', 'MF', 'HF', 'INMARSAT', 'satellite', 'vệ tinh', 'DSC', 'digital selective calling', 'distress alert', 'cảnh báo khẩn cấp', 'SAR', 'search and rescue', 'EPIRB', 'SART', 'NAVTEX', 'maritime safety information', 'MSI', 'radio installation', 'radio maintenance'] },
  { code: 'SOLAS V', standardType: 'SOLAS', category: 'Navigation', title: 'An toàn hàng hải', titleEn: 'Safety of navigation', keywords: ['collision', 'va chạm', 'đèn', 'shapes', 'tín hiệu âm thanh', 'navigational equipment', 'thiết bị hàng hải', 'charts', 'hải đồ', 'compass', 'la bàn', 'radar', 'ECDIS', 'GPS', 'AIS', 'automatic identification system', 'voyage data recorder', 'VDR', 'echo sounder', 'máy đo sâu', 'pilot ladder', 'thang hoa tiêu', 'navigation bridge visibility'] },
  { code: 'SOLAS VI', standardType: 'SOLAS', category: 'Cargo', title: 'Vận chuyển hàng hóa', titleEn: 'Carriage of cargoes', keywords: ['cargo', 'hàng hóa', 'stowage', 'xếp dỡ', 'securing', 'buộc chằng', 'lashing', 'dây buộc', 'cargo plan', 'kế hoạch xếp hàng', 'grain', 'ngũ cốc', 'dangerous goods', 'hàng nguy hiểm', 'IMDG Code', 'container', 'bulk cargo', 'hàng rời', 'stability', 'ổn định', 'trim', 'stress', 'ứng suất'] },
  { code: 'SOLAS XI-2', standardType: 'SOLAS', category: 'Security', title: 'Biện pháp đặc biệt tăng cường an ninh hàng hải', titleEn: 'Special measures to enhance maritime security', keywords: ['ISPS Code', 'maritime security', 'an ninh hàng hải', 'SSP', 'ship security plan', 'kế hoạch an ninh tàu', 'SSO', 'ship security officer', 'sĩ quan an ninh', 'CSO', 'company security officer', 'PFSO', 'security levels', 'cấp độ an ninh', 'security threats', 'security measures', 'access control', 'kiểm soát ra vào', 'security drills', 'diễn tập an ninh', 'DoS', 'declaration of security'] },

  // ── MARPOL ────────────────────────────────────────────────────────────────
  { code: 'MARPOL I', standardType: 'MARPOL', category: 'Pollution', title: 'Ngăn ngừa ô nhiễm dầu', titleEn: 'Prevention of pollution by oil', keywords: ['oil pollution', 'ô nhiễm dầu', 'oily water', 'nước dầu', 'bilge water', 'nước đáy tàu', 'oil discharge', 'xả dầu', 'ODMCS', 'oil discharge monitoring and control system', '15 ppm', 'oil record book', 'sổ nhật ký dầu', 'ORB', 'slop tank', 'két chứa cặn dầu', 'oil residue', 'cặn dầu', 'oily mixture', 'hỗn hợp dầu'] },
  { code: 'MARPOL II', standardType: 'MARPOL', category: 'Pollution', title: 'Ngăn ngừa ô nhiễm hóa chất lỏng', titleEn: 'Prevention of pollution by noxious liquid substances', keywords: ['chemicals', 'hóa chất', 'noxious liquid substances', 'NLS', 'chất lỏng độc hại', 'cargo record book', 'sổ nhật ký hàng', 'pre-wash', 'rửa trước', 'tank cleaning', 'rửa két', 'residue discharge', 'xả cặn', 'pollution category', 'loại ô nhiễm', 'P&A manual'] },
  { code: 'MARPOL III', standardType: 'MARPOL', category: 'Pollution', title: 'Ngăn ngừa ô nhiễm hàng hóa đóng gói', titleEn: 'Prevention of pollution by harmful substances in packaged form', keywords: ['packaged goods', 'hàng đóng gói', 'harmful substances', 'chất độc hại', 'IMDG Code', 'dangerous goods', 'hàng nguy hiểm', 'marine pollutants', 'chất ô nhiễm biển', 'packing', 'đóng gói', 'labeling', 'dán nhãn', 'marking', 'đánh dấu', 'stowage', 'xếp dỡ', 'segregation', 'phân tách'] },
  { code: 'MARPOL IV', standardType: 'MARPOL', category: 'Pollution', title: 'Ngăn ngừa ô nhiễm nước thải sinh hoạt', titleEn: 'Prevention of pollution by sewage', keywords: ['sewage', 'nước thải', 'toilet', 'nhà vệ sinh', 'blackwater', 'greywater', 'STP', 'sewage treatment plant', 'hệ thống xử lý nước thải', 'holding tank', 'két chứa', 'discharge', 'xả', 'comminuting', 'nghiền', 'disinfecting', 'khử trùng'] },
  { code: 'MARPOL V', standardType: 'MARPOL', category: 'Pollution', title: 'Ngăn ngừa ô nhiễm rác thải', titleEn: 'Prevention of pollution by garbage', keywords: ['rác thải', 'rác', 'garbage', 'nhựa', 'plastic', 'nhật ký rác', 'xử lý rác', 'incineration', 'đốt rác', 'waste', 'chất thải', 'food waste', 'rác thực phẩm', 'domestic waste', 'rác sinh hoạt', 'cooking oil', 'dầu ăn', 'operational waste', 'cargo residues', 'cặn hàng', 'garbage record book', 'GRB', 'garbage management plan', 'kế hoạch quản lý rác', 'special areas', 'khu vực đặc biệt'] },
  { code: 'MARPOL VI', standardType: 'MARPOL', category: 'Pollution', title: 'Ngăn ngừa ô nhiễm không khí', titleEn: 'Prevention of air pollution', keywords: ['air pollution', 'ô nhiễm không khí', 'exhaust gas', 'khí thải', 'SOx', 'sulfur oxide', 'lưu huỳnh', 'NOx', 'nitrogen oxide', 'ECA', 'emission control area', 'khu vực kiểm soát khí thải', 'fuel sulfur content', 'hàm lượng lưu huỳnh nhiên liệu', 'scrubber', 'thiết bị lọc khí', 'ODS', 'ozone depleting substances', 'refrigerant', 'chất làm lạnh', 'VOC', 'volatile organic compounds', 'EEXI', 'CII', 'carbon intensity indicator'] },

  // ── COLREGs ───────────────────────────────────────────────────────────────
  { code: 'COLREGs Rule 5', standardType: 'COLREGs', category: 'Navigation Rules', title: 'Quan sát', titleEn: 'Look-out', keywords: ['lookout', 'quan sát', 'watch', 'trực', 'sight', 'hearing', 'proper look-out', 'full appraisal', 'đánh giá đầy đủ', 'situation', 'tình huống', 'risk of collision', 'nguy cơ va chạm'] },
  { code: 'COLREGs Rule 6', standardType: 'COLREGs', category: 'Navigation Rules', title: 'Tốc độ an toàn', titleEn: 'Safe speed', keywords: ['safe speed', 'tốc độ an toàn', 'visibility', 'tầm nhìn', 'traffic density', 'mật độ giao thông', 'maneuverability', 'khả năng điều động', 'stopping distance', 'quãng đường dừng', 'radar', 'background light', 'ánh sáng nền', 'wind', 'gió', 'sea', 'sóng', 'current', 'dòng chảy', 'draft', 'mớn nước'] },
  { code: 'COLREGs Rule 7', standardType: 'COLREGs', category: 'Navigation Rules', title: 'Nguy cơ va chạm', titleEn: 'Risk of collision', keywords: ['risk of collision', 'nguy cơ va chạm', 'compass bearing', 'phương vị la bàn', 'relative bearing', 'phương vị tương đối', 'not appreciably changing', 'radar plotting', 'vẽ đồ radar', 'systematic observation', 'quan sát có hệ thống', 'assumptions', 'giả định', 'scanty information', 'thông tin ít ỏi'] },
  { code: 'COLREGs Rule 8', standardType: 'COLREGs', category: 'Navigation Rules', title: 'Hành động tránh va', titleEn: 'Action to avoid collision', keywords: ['action', 'hành động', 'avoid collision', 'tránh va', 'positive', 'good seamanship', 'nghiệp vụ tốt', 'ample time', 'alteration of course', 'thay đổi hướng', 'alteration of speed', 'thay đổi tốc độ', 'readily apparent', 'clear of the other vessel', 'safe distance', 'khoảng cách an toàn'] },
  { code: 'COLREGs Rule 9', standardType: 'COLREGs', category: 'Navigation Rules', title: 'Luồng hẹp', titleEn: 'Narrow channels', keywords: ['narrow channel', 'luồng hẹp', 'fairway', 'luồng lạch', 'starboard side', 'mạn phải', 'outer limit', 'giới hạn ngoài', 'not impede', 'không cản trở', 'safe passage', 'đi qua an toàn', 'fishing vessel', 'tàu đánh cá', 'crossing', 'cắt ngang', 'overtaking', 'vượt', 'bend', 'khúc cong', 'sound signal', 'tín hiệu âm'] },
  { code: 'COLREGs Rule 10', standardType: 'COLREGs', category: 'Navigation Rules', title: 'Hệ thống phân luồng giao thông', titleEn: 'Traffic separation schemes', keywords: ['TSS', 'traffic separation scheme', 'phân luồng giao thông', 'traffic lane', 'làn giao thông', 'separation zone', 'vùng phân cách', 'separation line', 'đường phân cách', 'general direction of traffic flow', 'hướng giao thông chung', 'inshore traffic zone', 'vùng giao thông ven bờ', 'small angle', 'góc nhỏ', 'crossing', 'cắt ngang', 'right angles', 'góc vuông', 'not impede', 'không cản trở'] },
  { code: 'COLREGs Rule 13', standardType: 'COLREGs', category: 'Navigation Rules', title: 'Vượt tàu', titleEn: 'Overtaking', keywords: ['overtaking', 'vượt', 'coming up', 'đuổi theo', '22.5 degrees', 'abaft the beam', 'phía sau mạn', 'keep out of the way', 'tránh đường', 'give-way vessel', 'tàu nhường đường', 'subsequent alteration', 'doubt', 'nghi ngờ', 'assume', 'giả định'] },
  { code: 'COLREGs Rule 14', standardType: 'COLREGs', category: 'Navigation Rules', title: 'Tàu đối mặt', titleEn: 'Head-on situation', keywords: ['head-on', 'đối mặt', 'meeting', 'gặp nhau', 'reciprocal courses', 'hướng ngược chiều', 'end on', 'mũi đối mũi', 'both masthead lights', 'alter course to starboard', 'đổi hướng sang phải', 'pass port to port', 'qua mạn trái đối mạn trái', 'doubt', 'nghi ngờ'] },
  { code: 'COLREGs Rule 15', standardType: 'COLREGs', category: 'Navigation Rules', title: 'Tàu cắt mặt', titleEn: 'Crossing situation', keywords: ['crossing', 'cắt mặt', 'starboard side', 'mạn phải', 'give way', 'nhường đường', 'keep out of the way', 'tránh đường', 'avoid crossing ahead', 'tránh cắt mũi', 'port side', 'mạn trái', 'stand-on vessel', 'tàu giữ hướng'] },
  { code: 'COLREGs Rule 16', standardType: 'COLREGs', category: 'Navigation Rules', title: 'Tàu nhường đường', titleEn: 'Action by give-way vessel', keywords: ['give-way vessel', 'tàu nhường đường', 'keep out of the way', 'tránh đường', 'early and substantial action', 'hành động sớm và rõ ràng', 'well clear', 'tránh xa', 'maneuver', 'điều động'] },
  { code: 'COLREGs Rule 17', standardType: 'COLREGs', category: 'Navigation Rules', title: 'Tàu giữ hướng', titleEn: 'Action by stand-on vessel', keywords: ['stand-on vessel', 'tàu giữ hướng', 'keep course and speed', 'giữ hướng và tốc độ', 'not taking appropriate action', 'may take action', 'best aid collision', 'tránh va tốt nhất', 'not alter to port', 'không đổi sang trái', 'vessel on port side', 'tàu ở mạn trái'] },
  { code: 'COLREGs Rule 18', standardType: 'COLREGs', category: 'Navigation Rules', title: 'Trách nhiệm giữa các loại tàu', titleEn: 'Responsibilities between vessels', keywords: ['power-driven vessel', 'tàu máy', 'give way to', 'nhường đường cho', 'not under command', 'mất khả năng điều khiển', 'restricted in ability to maneuver', 'hạn chế khả năng điều động', 'engaged in fishing', 'đang đánh cá', 'sailing vessel', 'tàu buồm', 'seaplane', 'thủy phi cơ', 'hierarchy', 'thứ bậc', 'not impede', 'safe passage'] },
  { code: 'COLREGs Part C', standardType: 'COLREGs', category: 'Lights and Shapes', title: 'Đèn và hình hiệu', titleEn: 'Lights and shapes', keywords: ['lights', 'đèn', 'shapes', 'hình hiệu', 'masthead light', 'đèn cột', 'sidelights', 'đèn mạn', 'sternlight', 'đèn đuôi', 'towing light', 'đèn kéo', 'all-round light', 'flashing light', 'đèn chớp', 'ball', 'hình cầu', 'cone', 'hình nón', 'cylinder', 'hình trụ', 'diamond', 'hình thoi', 'vessel at anchor', 'tàu neo', 'vessel aground', 'tàu mắc cạn', 'not under command', 'towing', 'kéo', 'pilot vessel', 'tàu hoa tiêu'] },
  { code: 'COLREGs Part D', standardType: 'COLREGs', category: 'Sound and Light Signals', title: 'Tín hiệu âm và ánh sáng', titleEn: 'Sound and light signals', keywords: ['sound signals', 'tín hiệu âm', 'light signals', 'tín hiệu ánh sáng', 'whistle', 'còi', 'horn', 'kèn', 'bell', 'chuông', 'gong', 'chiêng', 'short blast', 'tiếng ngắn', 'prolonged blast', 'tiếng dài', 'altering course to starboard', 'altering course to port', 'operating astern', 'chạy lùi', 'overtaking', 'doubt', 'nghi ngờ', 'restricted visibility', 'tầm nhìn hạn chế', 'vessel at anchor', 'vessel aground', 'pilot vessel'] },

  // ── IMO Codes ─────────────────────────────────────────────────────────────
  { code: 'IBC Code', standardType: 'IMO Codes', category: 'Chemical Tanker', title: 'Quy tắc vận chuyển hóa chất nguy hiểm bằng tàu biển', titleEn: 'International Code for the Construction and Equipment of Ships Carrying Dangerous Chemicals in Bulk', keywords: ['chemical tanker', 'tàu chở hóa chất', 'dangerous chemicals', 'hóa chất nguy hiểm', 'bulk liquid chemicals', 'hóa chất lỏng rời', 'cargo containment', 'bao chứa hàng', 'tank construction', 'kết cấu két', 'tank coating', 'lớp phủ két', 'compatibility', 'tương thích', 'segregation', 'phân tách', 'tank cleaning', 'rửa két', 'ventilation', 'thông gió', 'gas detection', 'phát hiện khí', 'PPE', 'MSDS', 'material safety data sheet'] },
  { code: 'IGC Code', standardType: 'IMO Codes', category: 'Gas Tanker', title: 'Quy tắc vận chuyển khí hóa lỏng bằng tàu biển', titleEn: 'International Code for the Construction and Equipment of Ships Carrying Liquefied Gases in Bulk', keywords: ['gas tanker', 'tàu chở khí', 'LNG', 'liquefied natural gas', 'khí tự nhiên hóa lỏng', 'LPG', 'liquefied petroleum gas', 'khí dầu mỏ hóa lỏng', 'cryogenic', 'nhiệt độ cực thấp', 'refrigeration', 'làm lạnh', 'insulation', 'cách nhiệt', 'cargo containment system', 'hệ thống bao chứa hàng', 'membrane tank', 'két màng', 'independent tank', 'két độc lập', 'boil-off gas', 'khí bay hơi', 'BOG', 'reliquefaction', 'hóa lỏng lại', 'gas-free', 'xả khí', 'inerting', 'làm trơ'] },
  { code: 'IMDG Code', standardType: 'IMO Codes', category: 'Dangerous Goods', title: 'Quy tắc vận chuyển hàng nguy hiểm đóng gói bằng đường biển', titleEn: 'International Maritime Dangerous Goods Code', keywords: ['dangerous goods', 'hàng nguy hiểm', 'hazardous materials', 'vật liệu nguy hiểm', 'explosives', 'chất nổ', 'flammable liquids', 'chất lỏng dễ cháy', 'flammable solids', 'chất rắn dễ cháy', 'oxidizing substances', 'chất oxy hóa', 'toxic substances', 'chất độc', 'radioactive', 'phóng xạ', 'corrosive', 'ăn mòn', 'packing group', 'nhóm đóng gói', 'UN number', 'mã UN', 'proper shipping name', 'tên vận chuyển chính xác', 'labeling', 'dán nhãn', 'marking', 'đánh dấu', 'placarding', 'biển báo', 'segregation', 'phân tách', 'stowage', 'xếp dỡ', 'marine pollutant', 'chất ô nhiễm biển'] },
];
